# tasks file for nginx
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart_nginx
  when: "'internal_nginx' in group_names or 'external_nginx' in group_names"