---
- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: yes

- name: Backup existing Nginx repository file
  ansible.builtin.shell:
    cmd: "cp {{ nginx_repo_file }} {{ nginx_backup_file }}"
  args:
    creates: "{{ nginx_backup_file }}"
  changed_when: false
  ignore_errors: yes

- name: Import Nginx signing key
  ansible.builtin.command:
    cmd: curl -fsSL {{ nginx_signing_key_url }} | sudo gpg --dearmor -o {{ nginx_keyring_path }}
  args:
    creates: "{{ nginx_keyring_path }}"

- name: Verify Nginx signing key
  ansible.builtin.command:
    cmd: gpg --dry-run --quiet --no-keyring --import --import-options import-show {{ nginx_keyring_path }}
  register: gpg_key_check

- name: Ensure the Nginx signing key is correct
  ansible.builtin.assert:
    that:
      - "'573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62' in gpg_key_check.stdout"
    fail_msg: "Nginx signing key fingerprint does not match."

- name: Generate Nginx repository file
  ansible.builtin.copy:
    content: |
      deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] {{ nginx_repo_url }}
    dest: "{{ nginx_repo_file }}"
    backup: yes

- name: Set up repository pinning
  ansible.builtin.copy:
    dest: "{{ nginx_pin_file }}"
    content: "{{ nginx_pin }}"

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: "nginx={{ nginx_version }}"
    state: present

- name: Ensure Nginx service is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Check Nginx Version
  ansible.builtin.shell:
    cmd: "nginx -v 2>&1 | awk -F '/' '{print $2}' | cut -d ' ' -f 1"
  register: nginx_version_output
  changed_when: false

- name: Display Nginx Version
  ansible.builtin.debug:
    msg: "Nginx Version is {{ nginx_version_output.stdout }}"
