---
- name: Install prerequisites
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: yes

- name: Import Nginx signing key
  ansible.builtin.shell:
    cmd: curl -fsSL {{ nginx_signing_key_url }} | sudo gpg --dearmor -o {{ nginx_keyring_path }}
  args:
    creates: "{{ nginx_keyring_path }}"

- name: Generate Nginx repository file
  ansible.builtin.copy:
    content: |
      deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] {{ nginx_repo_url }}
    dest: "{{ nginx_repo_file }}"
    backup: yes

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: "nginx={{ nginx_version }}"
    state: present

- name: Ensure Nginx service is started and enabled
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

- name: Check Nginx Version
  ansible.builtin.shell:
    cmd: "nginx -v 2>&1 | awk -F '/' '{print $2}' | cut -d ' ' -f 1"
  register: nginx_version_output
  changed_when: false

- name: Display Nginx Version
  ansible.builtin.debug:
    msg: "Nginx Version is {{ nginx_version_output.stdout }}"
