- name: Create User Kafka
  user:
    name: kafka
    home: /home/kafka  
    shell: /bin/bash

- name: Update password to User 'kafka'    
  user:
    name: kafka
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"
  when: newpassword is defined

- name: Add kafka user to sudo group
  user:
    name: kafka
    groups: sudo


- name: Download Kafka binaries using wget
  command: "wget -O /home/kafka/kafka.tgz {{ kafka_url }}"
  register: download_result
  ignore_errors: true

- name: Debug download result
  debug:
    var: download_result

- name: Extract Kafka binaries
  unarchive:
    src: "/home/kafka/kafka.tgz"
    dest: "/home/kafka"
    remote_src: yes
  when: download_result is succeeded and download_result.rc == 1

