---
# Tasks file for setting up Redis

# - name: SetUp Proxy
#   include_tasks: proxy.yml

- name: Install Redis
  include_tasks: redis.yml

- name: Install Redis Sentinel
  include_tasks: sentinel.yml

- name: Configure Redis on Master Node
  include_tasks: masterconf.yml
  when: "'RedisMaster' in group_names"

- name: Configure Redis on Replica Nodes 
  include_tasks: slaveconf.yml
  when: "'RedisSlave' in group_names"

- name: Configure Redis Sentinel
  include_tasks: sentinelconf.yml