- name: Check if redis.conf file exists
  ansible.builtin.stat:
    path: /etc/redis/redis.conf
  register: redis_file_stat

- name: Store current block content of /etc/redis/redis.conf
  ansible.builtin.shell:
    cmd: cat /etc/redis/redis.conf
  register: redis_block_content
  when: redis_file_stat.stat.exists

- name: Uncomment and edit Redis configurations
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^\s*#?\s*{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  loop:
    - { regexp: 'bind', line: "bind 0.0.0.0" }
    - { regexp: 'requirepass', line: "requirepass {{ redis_master_password }}" }
    - { regexp: 'masterauth', line: "masterauth {{ redis_master_password }}" }

- name: Store the new block content of /etc/redis/redis.conf
  ansible.builtin.shell:
    cmd: cat /etc/redis/redis.conf
  register: redis_blockinfile_result

- name: Backup Redis configuration file
  ansible.builtin.copy:
    content: "{{ redis_block_content.stdout }}"
    dest: "/etc/redis/redis.conf_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}.bkp"
    remote_src: yes
  when:
    - redis_file_stat.stat.exists
    - redis_block_content.stdout != redis_blockinfile_result.stdout

- name: Restart Redis service
  ansible.builtin.service:
    name: redis-server
    state: restarted
