- name: Check if redis.conf file exists in Redis Slave nodes
  ansible.builtin.stat:
    path: /etc/redis/redis.conf
  register: redisfile_stat

- name: Store current block content of /etc/redis/redis.conf in Redis Slave nodes
  ansible.builtin.shell:
    cmd: cat /etc/redis/redis.conf
  register: redisblock_content
  when: redisfile_stat.stat.exists

- name: Update Redis configuration in redis.conf for slave nodes
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^\s*#?\s*{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  loop:
    - { regexp: 'bind', line: "bind 0.0.0.0" }
    - { regexp: 'requirepass', line: "requirepass {{ redis_master_password }}" }
    - { regexp: 'masterauth', line: "masterauth {{ redis_master_password }}" }
    - { regexp: 'replicaof', line: "replicaof {{ redis_master }} {{ redis_port }}" }

- name: Store the new block content of /etc/redis/redis.conf in Redis Slave nodes
  ansible.builtin.shell:
    cmd: cat /etc/redis/redis.conf
  register: redisblockinfile_result

- name: Backup Redis configuration file in Redis Slave nodes
  ansible.builtin.copy:
    content: "{{ redisblock_content.stdout }}"
    dest: "/etc/redis/redis.conf_{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}_{{ ansible_date_time.minute }}.bak"
    remote_src: yes
  when:
    - redisfile_stat.stat.exists
    - redisblock_content.stdout != redisblockinfile_result.stdout

- name: Restart Redis service in Redis Slave nodes
  ansible.builtin.service:
    name: redis-server
    state: restarted
